apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-aurora
  labels:
    app: lord-eclipse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lord-eclipse
  template:
    metadata:
      labels:
        app: lord-eclipse
    spec:
      containers:
      - name: lord-eclipse-app
        image: tumbadenazarick/projeto-aurora:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: projeto-aurora-service
spec:
  selector:
    app: lord-eclipse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
